server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.127.100:3306/blog?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: Xiaoxin.sql123
  data:
    redis:
      host: 192.168.127.100
      port: 6379
      database: 0

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://192.168.127.100:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: blog

springdoc:
  default-flat-param-object: true